/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as livestockManagerSol from "./LivestockManager.sol";
export type { livestockManagerSol };
export type { AssetShareToken } from "./AssetShareToken";
export type { Greeter } from "./Greeter";
export type { LivestockAssetNFT } from "./LivestockAssetNFT";
export type { TestStablecoin } from "./TestStablecoin";
