/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILivestockAssetNFT } from "./ILivestockAssetNFT";
export type { LivestockManager } from "./LivestockManager";
