/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILivestockAssetNFT,
  ILivestockAssetNFTInterface,
} from "../../../contracts/LivestockManager.sol/ILivestockAssetNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "safeMint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILivestockAssetNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ILivestockAssetNFTInterface {
    return new Interface(_abi) as ILivestockAssetNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILivestockAssetNFT {
    return new Contract(address, _abi, runner) as unknown as ILivestockAssetNFT;
  }
}
